development:
  adapter: postgresql
  database: c2c_development
  host: localhost

test:
  adapter: postgresql
  database: c2c_test
  host: localhost

production:
  adapter: postgresql
  database: c2c_production
  host: localhost
